config/routes.rb
MekWarsOpsWikiGenerator::Application.routes.draw do
  root to: "generate_wiki#form" 

  get "generate_wiki/form"

  post "generate_wiki/upload"

  resources :operation_types

  resources :operation_settings

end

app/models/operation_setting.rb
class OperationSetting < ActiveRecord::Base
  attr_accessible :display, :identifier, :value

  belongs_to :operation_type

  def self.default_value_for( identifier )
    find_by_identifier( identifier ).try( :default_value )
  end
end

app/models/operation_type.rb
class OperationType < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/generate_wiki_controller.rb
class GenerateWikiController < ApplicationController
  layout false
  def form
  end

  def another_file
  end

  def upload
    @files = params[:op_file]
    if @files.present?
      io_string = parse_files
      io_string.rewind
      send_data io_string.read, filename: "wiki_ops.zip", type: "application/zip"
    else
      redirect_to root_path, notice: "Please Upload a File"
    end
  end

  private

  def parse_files
    Zip::ZipOutputStream::write_buffer do |zipfile|
      @files.each do |op_file|
        if op_name( op_file )
          zipfile.put_next_entry( op_name( op_file ) )
          zipfile.write( parse_file( op_file ) )
        end
      end
    end
  end

  def parse_file( op_file )
    @passed_in_settings = {}
    op_file.read.each_line do |line|
      key, value = line.split( "=" )
      if key.present? and value.present?
        @passed_in_settings[key.strip] = value.strip
      end
    end
    render_to_string :upload
  end

  def op_name( op_file )
    match = op_file.original_filename.match /\A(.*)\.txt\Z/
    match.try( :[], 1 )
  end
end

app/controllers/operation_settings_controller.rb
class OperationSettingsController < ApplicationController
  # GET /operation_settings
  # GET /operation_settings.json
  def index
    @operation_settings = OperationSetting.order( "export desc, identifier" ).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @operation_settings }
    end
  end

  # GET /operation_settings/1
  # GET /operation_settings/1.json
  def show
    @operation_setting = OperationSetting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @operation_setting }
    end
  end

  # GET /operation_settings/new
  # GET /operation_settings/new.json
  def new
    @operation_setting = OperationSetting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @operation_setting }
    end
  end

  # GET /operation_settings/1/edit
  def edit
    @operation_setting = OperationSetting.find(params[:id])
  end

  # POST /operation_settings
  # POST /operation_settings.json
  def create
    @operation_setting = OperationSetting.new(params[:operation_setting])

    respond_to do |format|
      if @operation_setting.save
        format.html { redirect_to @operation_setting, notice: 'Operation setting was successfully created.' }
        format.json { render json: @operation_setting, status: :created, location: @operation_setting }
      else
        format.html { render action: "new" }
        format.json { render json: @operation_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /operation_settings/1
  # PUT /operation_settings/1.json
  def update
    @operation_setting = OperationSetting.find(params[:id])

    respond_to do |format|
      if @operation_setting.update_attributes(params[:operation_setting])
        format.html { redirect_to @operation_setting, notice: 'Operation setting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @operation_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operation_settings/1
  # DELETE /operation_settings/1.json
  def destroy
    @operation_setting = OperationSetting.find(params[:id])
    @operation_setting.destroy

    respond_to do |format|
      format.html { redirect_to operation_settings_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/operation_types_controller.rb
class OperationTypesController < ApplicationController
  # GET /operation_types
  # GET /operation_types.json
  def index
    @operation_types = OperationType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @operation_types }
    end
  end

  # GET /operation_types/1
  # GET /operation_types/1.json
  def show
    @operation_type = OperationType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @operation_type }
    end
  end

  # GET /operation_types/new
  # GET /operation_types/new.json
  def new
    @operation_type = OperationType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @operation_type }
    end
  end

  # GET /operation_types/1/edit
  def edit
    @operation_type = OperationType.find(params[:id])
  end

  # POST /operation_types
  # POST /operation_types.json
  def create
    @operation_type = OperationType.new(params[:operation_type])

    respond_to do |format|
      if @operation_type.save
        format.html { redirect_to @operation_type, notice: 'Operation type was successfully created.' }
        format.json { render json: @operation_type, status: :created, location: @operation_type }
      else
        format.html { render action: "new" }
        format.json { render json: @operation_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /operation_types/1
  # PUT /operation_types/1.json
  def update
    @operation_type = OperationType.find(params[:id])

    respond_to do |format|
      if @operation_type.update_attributes(params[:operation_type])
        format.html { redirect_to @operation_type, notice: 'Operation type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @operation_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operation_types/1
  # DELETE /operation_types/1.json
  def destroy
    @operation_type = OperationType.find(params[:id])
    @operation_type.destroy

    respond_to do |format|
      format.html { redirect_to operation_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/generate_wiki_helper.rb
module GenerateWikiHelper
  def display_value( value )
    case value
    when "t"
      "true"
    when "f"
      "false"
    else
      value
    end
  end

  def value_for_identifier( identifier )
    @passed_in_settings[identifier] || OperationSetting.default_value_for( identifier )
  end

  def value?( identifier )
    value = display_value( value_for_identifier( identifier ) )
    value.present? and value != "false" and value != "0"
  end

  def any_values?( identifiers )
    !identifiers.empty? and identifiers.any? {|i| value?( i ) }
  end
end

app/helpers/operation_settings_helper.rb
module OperationSettingsHelper
end

app/helpers/operation_types_helper.rb
module OperationTypesHelper
end

app/views/generate_wiki/_army_composition.html.haml
\|-
\! colspan="4"| #{subject}
\|-
= render partial: "range", locals: { range_name: "BV", identifier1: "Min#{subject}BV", identifier2: "Max#{subject}BV" }
= render partial: "standard_setting", locals: { name: "Maximum BV Spread", identifier: "Max#{subject}UnitBVSpread" }
\|-
= render partial: "standard_setting", locals: { name: "Meks Allowed", identifier: "#{subject}AllowedMeks" }
= render partial: "range", locals: { range_name: "Mek", identifier1: "Min#{subject}Meks", identifier2: "Max#{subject}Meks" }
\|-
= render partial: "standard_setting", locals: { name: "Vehicles Allowed", identifier: "#{subject}AllowedVehs" }
= render partial: "range", locals: { range_name: "Vehicle", identifier1: "Min#{subject}Vehicles", identifier2: "Max#{subject}Vehicles" }
\|-
= render partial: "standard_setting", locals: { name: "Infantry Allowed", identifier: "#{subject}AllowedInf" }
= render partial: "range", locals: { range_name: "Infantry", identifier1: "Min#{subject}Infantry", identifier2: "Max#{subject}Infantry" }
\|-
= render partial: "standard_setting", locals: { name: "Aeros Allowed", identifier: "#{subject}AllowedAeros" }
= render partial: "range", locals: { range_name: "Aeros", identifier1: "Min#{subject}Aero", identifier2: "Max#{subject}Aero" }
\|-

app/views/generate_wiki/_op_file.html.haml
= file_field_tag "op_file[]", id: "op_file_#{Time.now.to_i}"

app/views/generate_wiki/_participants.html.haml
\|-
\! colspan="4"| #{subject}
\|-
= render partial: "range", locals: { range_name: "Experience", identifier1: "Min#{subject}XP", identifier2: "Max#{subject}XP" }
= render partial: "range", locals: { range_name: "Rating", identifier1: "Min#{subject}Rating", identifier2: "Max#{subject}Rating" }
\|-

app/views/generate_wiki/_range.html.haml
= "| #{range_name} Range:"
= "| #{display_value value_for_identifier( identifier1 )}-#{display_value value_for_identifier( identifier2 )}"

app/views/generate_wiki/_standard_setting.html.haml
= "| #{name}:"
= "| #{display_value value_for_identifier( identifier )}"

app/views/generate_wiki/_unit_restrictions.html.haml
\|-
\! colspan="8"| #{subject}
\|-
= render partial: "standard_setting", locals: { name: "Max Tonnage Per Unit", identifier: "Max#{subject}UnitTonnage" }
= render partial: "standard_setting", locals: { name: "Minimum Walking MP", identifier: "Min#{subject}Walk" }
= render partial: "standard_setting", locals: { name: "Minimum Jumping MP", identifier: "Min#{subject}Jump" }
= render partial: "standard_setting", locals: { name: "Maximum Jumping MP", identifier: "Max#{subject}Jump" }
\|-

app/views/generate_wiki/form.html.haml
%p Please upload MekWars op-files (i.e. "Strategic - Hit'n'Run.txt" or "Conquer.txt")
%p You will receive a zip file containing wiki-markup versions of the ops.
= form_tag( generate_wiki_upload_path, multipart: true ) do
  = select_tag :operation_type, options_for_select( OperationType.order( :name ).collect {|o| [ o.name, o.id ] }, params[:operation_type] || OperationType.find_by_name( "Short" ).id )
  = submit_tag "Upload"
  - 15.times do |i|
    %p
      = file_field_tag "op_file[]", id: "op_file_#{i}"

app/views/generate_wiki/upload.html.haml
\== Force Description ==
\==== Army Composition ====
\{| width="80%"
= render partial: "army_composition", locals: { subject: "Attacker" }
= render partial: "army_composition", locals: { subject: "Defender" }
\|}
\==== Unit Restrictions ====
\{| width="80%"
= render partial: "unit_restrictions", locals: { subject: "Attacker" }
= render partial: "unit_restrictions", locals: { subject: "Defender" }
\|}
\== Operation Description ==
\==== Valid Targets ====
\{| width="80%"
= render partial: "standard_setting", locals: { name: "Only Non-Capital Worlds", identifier: "OnlyAgainstNonHomeWorlds" }
= render partial: "standard_setting", locals: { name: "Only Non-Factory Worlds", identifier: "OnlyAgainstNonFactoryWorlds" }
\|-
= render partial: "standard_setting", locals: { name: "Only Factory Worlds", identifier: "OnlyAgainstFactoryWorlds" }
= render partial: "standard_setting", locals: { name: "Only Capital Worlds", identifier: "OnlyAgainstHomeWorlds" }
\|}
\==== Deployment ====
\{| width="80%"
= render partial: "standard_setting", locals: { name: "Random", identifier: "RandomDeployment" }
= "| Chance for Edge for both armies:"
= "| #{ any_values?( [ "DeployNorthwest", "DeployNorth", "DeployNortheast", "DeployWest", "DeployEast", "DeploySouthwest", "DeploySouth", "DeploySoutheast" ] ) ? "true" : "false" }"
\|-
= "| Chance for Deep:"
= "| #{ any_values?( [ "DeployNorthwestdeep", "DeployNorthdeep", "DeployNortheastdeep", "DeployWestdeep", "DeployEastdeep", "DeploySouthwestdeep", "DeploySouthdeep", "DeploySoutheastdeep" ] ) ? "true" : "false" }"
= "| Chance for one army Center and one army Edge:"
= "| #{ value?( "DeployCenter" ) ? "true" : "false" }"
\|}
\==== Participants ====
\{| width="80%"
= render partial: "participants", locals: { subject: "Attacker" }
= render partial: "participants", locals: { subject: "Defender" }
\|}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MekWarsOpsWikiGenerator</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/operation_settings/_form.html.erb
<%= form_for(@operation_setting) do |f| %>
  <% if @operation_setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operation_setting.errors.count, "error") %> prohibited this operation_setting from being saved:</h2>

      <ul>
      <% @operation_setting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :identifier %><br />
    <%= f.text_area :identifier %>
  </div>
  <div class="field">
    <%= f.label :default_value %><br />
    <%= f.text_area :default_value %>
  </div>
  <div class="field">
    <%= f.label :display %><br />
    <%= f.text_area :display %>
  </div>
  <div class="field">
    <%= f.label :operation_type %><br />
    <%= f.select :operation_type, OperationType.order( :name ).all %>
  </div>
  <div class="field">
    <%= f.label :export %><br />
    <%= f.check_box :export %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/operation_settings/edit.html.erb
<h1>Editing operation_setting</h1>

<%= render 'form' %>

<%= link_to 'Show', @operation_setting %> |
<%= link_to 'Back', operation_settings_path %>

app/views/operation_settings/index.html.erb
<h1>Listing operation_settings</h1>

<table>
  <tr>
    <th>Identifier</th>
    <th>Default</th>
    <th>Display</th>
    <th>Operation Type</th>
    <th>Export</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @operation_settings.each do |operation_setting| %>
  <tr>
    <td><%= operation_setting.identifier %></td>
    <td><%= operation_setting.default_value %></td>
    <td><%= operation_setting.display %></td>
    <td><%= operation_setting.operation_type.name %></td>
    <td><%= operation_setting.export %></td>
    <td><%= link_to 'Show', operation_setting %></td>
    <td><%= link_to 'Edit', edit_operation_setting_path(operation_setting) %></td>
    <td><%= link_to 'Destroy', operation_setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Operation setting', new_operation_setting_path %>

app/views/operation_settings/new.html.erb
<h1>New operation_setting</h1>

<%= render 'form' %>

<%= link_to 'Back', operation_settings_path %>

app/views/operation_settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Identifier:</b>
  <%= @operation_setting.identifier %>
</p>

<p>
  <b>Default:</b>
  <%= @operation_setting.default_value %>
</p>

<p>
  <b>Display:</b>
  <%= @operation_setting.display %>
</p>

<p>
  <b>Operation Type:</b>
  <%= @operation_setting.operation_type.name %>
</p>

<p>
  <b>Export:</b>
  <%= @operation_setting.export %>
</p>


<%= link_to 'Edit', edit_operation_setting_path(@operation_setting) %> |
<%= link_to 'Back', operation_settings_path %>

app/views/operation_types/_form.html.erb
<%= form_for(@operation_type) do |f| %>
  <% if @operation_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operation_type.errors.count, "error") %> prohibited this operation_type from being saved:</h2>

      <ul>
      <% @operation_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :export %><br />
    <%= f.check_box :export %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/operation_types/edit.html.erb
<h1>Editing operation_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @operation_type %> |
<%= link_to 'Back', operation_types_path %>

app/views/operation_types/index.html.erb
<h1>Listing operation_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Export</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @operation_types.each do |operation_type| %>
  <tr>
    <td><%= operation_type.name %></td>
    <td><%= operation_type.export %></td>
    <td><%= link_to 'Show', operation_type %></td>
    <td><%= link_to 'Edit', edit_operation_type_path(operation_type) %></td>
    <td><%= link_to 'Destroy', operation_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Operation type', new_operation_type_path %>

app/views/operation_types/new.html.erb
<h1>New operation_type</h1>

<%= render 'form' %>

<%= link_to 'Back', operation_types_path %>

app/views/operation_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @operation_type.name %>
</p>

<p>
  <b>Export:</b>
  <%= @operation_type.export %>
</p>


<%= link_to 'Edit', edit_operation_type_path(@operation_type) %> |
<%= link_to 'Back', operation_types_path %>